acts_camdram_group_toolbar:
    pattern: /groups/toolbar
    defaults: { _controller: ActsCamdramBundle:Group:toolbar }
acts_camdram_groups:
    type:     rest
    prefix:   /
    resource: "Acts\CamdramBundle\Controller\GroupController"
acts_camdram_user_toolbar:
    pattern: /groups/toolbar
    defaults: { _controller: ActsCamdramBundle:User:toolbar }
acts_camdram_users:
    type:     rest
    prefix:   /
    resource: "Acts\CamdramBundle\Controller\UserController"