acts_camdram_contact_us:
    path: /contact-us
    defaults: { _controller: ActsCamdramBundle:ContactUs:index }
    methods:  [GET]
acts_camdram_contact_us_send:
    path: /contact-us
    defaults: { _controller: ActsCamdramBundle:ContactUs:send }
    methods:  [POST]
acts_camdram_contact_us_sent:
    path: /contact-us/sent
    defaults: { _controller: ActsCamdramBundle:ContactUs:sent }
