acts_camdram_homepage:
    pattern:  /
    defaults: { _controller: ActsCamdramBundle:Default:index }
acts_camdram_homepage_statistics:
    pattern:  /home/statistics
    defaults: { _controller: ActsCamdramBundle:Default:statistics }
acts_camdram_homepage_vacancies:
    pattern:  /home/vacancies
    defaults: { _controller: ActsCamdramBundle:Default:vacancies }