acts_camdram_development:
    path: /
    defaults: { _controller: ActsCamdramBundle:Development:index }
acts_camdram_development_activity:
    path: /activity
    defaults: { _controller: ActsCamdramBundle:Development:activity }
