acts_camdram_diary:
    pattern:  /
    defaults: { _controller: ActsCamdramBundle:Diary:index }

acts_camdram_diary_period:
    pattern:  /period/{id}
    defaults: { _controller: ActsCamdramBundle:Diary:periodDiary }
