acts_camdram_diary:
    pattern:  /
    defaults: { _controller: ActsCamdramBundle:Diary:index }

acts_camdram_diary_period:
    pattern:  /period
    defaults: { _controller: ActsCamdramBundle:Diary:period }
