acts_camdram_diary_date:
    pattern:  /{start}.{_format}
    defaults:
        _controller: ActsCamdramBundle:Diary:date
        _format: html
    requirements:
        start: "[0-9]{4}\-[0-9]{2}\-[0-9]{2}"

acts_camdram_diary_year:
    pattern:  /{year}.{_format}
    defaults:
        _controller: ActsCamdramBundle:Diary:year
        _format: html
    requirements:
        year: "[0-9]{4}"

acts_camdram_diary_period:
    pattern:  /{year}/{period}.{_format}
    defaults:
        _controller: ActsCamdramBundle:Diary:period
        _format: html
    requirements:
        year: "[0-9]{4}"

acts_camdram_diary_week:
    pattern:  /{year}/{period}/{week}.{_format}
    defaults:
        _controller: ActsCamdramBundle:Diary:week
        _format: html
    requirements:
        year: "[0-9]{4}"

acts_camdram_diary_single_week:
    pattern:  /week/{date}.{_format}
    defaults:
        _controller: ActsCamdramBundle:Diary:singleWeek
        _format: html

