acts_camdram_diary:
    pattern:  /
    defaults: { _controller: ActsCamdramBundle:Diary:index }

acts_camdram_diary_period:
    pattern:  /period/{id}
    defaults: { _controller: ActsCamdramBundle:Diary:diary }

acts_camdram_diary_content:
    pattern: /content/{direction}/{last_date}
    defaults: { _controller: ActsCamdramBundle:Diary:content }