acts_camdram_venues_map:
    pattern: /venues/map/{identifier}
    defaults: { _controller: ActsCamdramBundle:Venue:map, identifier: ~ }

acts_camdram_shows:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\ShowController"

acts_camdram_shows_techieadverts:
    type:   rest
    parent: acts_camdram_shows
    resource: "Acts\CamdramBundle\Controller\Show\TechieAdvertController"
acts_camdram_shows_auditions:
    type:   rest
    parent: acts_camdram_shows
    resource: "Acts\CamdramBundle\Controller\Show\AuditionController"
acts_camdram_shows_applications:
    type:   rest
    parent: acts_camdram_shows
    resource: "Acts\CamdramBundle\Controller\Show\ApplicationController"
acts_camdram_shows_admins:
    type:   rest
    parent: acts_camdram_shows
    resource: "Acts\CamdramBundle\Controller\Show\AdminController"
acts_camdram_shows_roles:
    type:   rest
    parent: acts_camdram_shows
    resource: "Acts\CamdramBundle\Controller\Show\RoleController"

acts_camdram_people:
    type:     rest
    resource: Acts\CamdramBundle\Controller\PersonController
acts_camdram_societies:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\SocietyController"
acts_camdram_venues:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\VenueController"

acts_camdram_search:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\SearchController"

acts_camdram_termdates:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\TermDateController"

acts_camdram_applications:
    type:     rest
    prefix: /vacancies
    resource: "Acts\CamdramBundle\Controller\ApplicationController"
acts_camdram_auditions:
    type:     rest
    prefix: /vacancies
    resource: "Acts\CamdramBundle\Controller\AuditionController"
acts_camdram_techieadverts:
    type:     rest
    prefix: /vacancies
    resource: "Acts\CamdramBundle\Controller\TechieAdvertController"

acts_camdram_timeperiods:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\TimePeriodController"

acts_camdram_show_admin:
    pattern: /show-admin
    defaults: { _controller: ActsCamdramBundle:ShowAdmin:cget }

acts_camdram_show_unauthorised:
    pattern: /show-admin/unauthorised
    defaults: { _controller: ActsCamdramBundle:ShowAdmin:cgetUnauthorised }
