language: php
matrix:
  include:
    - php: 7.0
    - php: 7.2
  fast_finish: true
cache:
  yarn: true
  directories:
  - $HOME/.composer/cache/files
services:
  - elasticsearch
  - mysql
before_script:
- cp app/config/parameters.travis.yml app/config/parameters.yml
- phpenv config-rm xdebug.ini
- composer selfupdate
- composer install --no-interaction
- yarn install
- yarn build
script:
- "./runtests"
- "./check_dev_setup"