language: php
matrix:
  include:
    - php: 7.0
    - php: 7.2
  fast_finish: true
cache:
  directories:
  - $HOME/.composer/cache/files
services:
  - elasticsearch
before_script:
- cp app/config/parameters.test.yml app/config/parameters.yml
- phpenv config-rm xdebug.ini
- composer selfupdate
- composer install --no-interaction
script:
- "./runtests"
- "./check_dev_setup"