language: php
matrix:
  include:
    - php: 5.6
    - php: 7.0
  fast_finish: true
services:
  - elasticsearch
before_script:
- cp app/config/parameters.test.yml app/config/parameters.yml
- composer selfupdate
- composer install --no-interaction
script:
- "./runtests"
- "./check_dev_setup"