language: php
sudo: required
matrix:
  include:
    - php: 5.6
    - php: 7.0
  fast_finish: true
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.8.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.8.deb && sudo service elasticsearch restart
before_script:
- cp app/config/parameters.test.yml app/config/parameters.yml
- composer selfupdate
- composer install --no-interaction
script:
- "./runtests"
