language: php
sudo: required
matrix:
  include:
    - php: 5.6
    - php: 7.0
  fast_finish: true
before_script:
- cp app/config/parameters.test.yml app/config/parameters.yml
- composer selfupdate
- composer install --no-interaction
- "./install-sphinx"
script:
- "./runtests sphinx"
- "./runtests"
