os: linux
language: php
dist: xenial
jobs:
  include:
    - php: 7.3
  fast_finish: true
cache:
  directories:
  - $HOME/.composer/cache/files
services:
  - mysql
before_script:
  # Disable xdebug for speedup
- phpenv config-rm xdebug.ini
  # Enable search listeners via paramaters.yml
- cp app/config/parameters.travis.yml app/config/parameters.yml
  # Install deps. `--no-interaction` causes paramters.yml to be populated with default values
- travis_retry composer install --no-interaction
- nvm install 10.15
- yarn install
script:
- "yarn build"
- "./runtests"
- "./check_dev_setup"
