language: php
matrix:
  include:
    - php: 7.0
    - php: 7.2
  fast_finish: true
cache:
  directories:
  - $HOME/.composer/cache/files
services:
  - elasticsearch
  - mysql
before_script:
  # Enable search listeners via paramaters.yml
- echo -e "parameters:\n\tsearch_enable_listeners: true" > app/config/parameters.yml
  # Disable xdebug for speedup
- phpenv config-rm xdebug.ini
  # Install deps. `--no-interaction` causes paramters.yml to be populated with default values
- composer install --no-interaction
script:
- "./runtests"
- "./check_dev_setup"