camdram_security_entry_point:
    pattern: /connect/{service}
    defaults: { _controller: ActsCamdramSecurityBundle:Default:redirect }

camdram_security_local_login:
    pattern: /login/form
    defaults: { _controller: ActsCamdramSecurityBundle:Default:loginForm }

camdram_security_login:
    pattern: /login/{service}
    defaults: { service: ~ }

camdram_security_confirm_add_identity:
    pattern: /auth/confirm-add-identity
    defaults: { _controller: ActsCamdramSecurityBundle:Default:confirmAddIdentity }

camdram_security_connect_users:
    pattern: /auth/connect-users
    defaults: { _controller: ActsCamdramSecurityBundle:Default:connectUsers }

camdram_security_connect_users_process:
    pattern: /auth/connect-users-process
    defaults: { _controller: ActsCamdramSecurityBundle:Default:connectUsersProcess }

camdram_security_no_existing_user:
    pattern: /auth/check-new-user
    defaults: { _controller: ActsCamdramSecurityBundle:Default:noExistingUser }

camdram_security_new_user:
    pattern: /auth/new-user
    defaults: { _controller: ActsCamdramSecurityBundle:Default:newUser }

camdram_security_setup:
    pattern: /auth/setup
    defaults: { _controller: ActsCamdramSecurityBundle:Setup:default }

camdram_security_setup_link_person:
    pattern: /auth/setup/person
    defaults: { _controller: ActsCamdramSecurityBundle:Setup:linkPerson }

camdram_security_setup_roles:
    pattern: /auth/setup/roles
    defaults: { _controller: ActsCamdramSecurityBundle:Setup:roles }