acts_camdram_security_login:
    pattern:   /login
    defaults:  {  _controller: ActsCamdramSecurityBundle:Default:login }
acts_camdram_security_login_check:
    pattern:   /login_check
acts_camdram_security_link_user:
    pattern:   /link-user
    defaults: { _controller: ActsCamdramSecurityBundle:Default:linkUser }
acts_camdram_security_create_account:
    pattern:   /create-account
    defaults: { _controller: ActsCamdramSecurityBundle:Default:createAccount }
acts_camdram_security_create_account_complete:
    pattern:   /create-account-complete
    defaults: { _controller: ActsCamdramSecurityBundle:Default:createAccountComplete }
acts_camdram_security_confirm_email:
    pattern:   /confirm-email/{email}/{token}
    defaults: { _controller: ActsCamdramSecurityBundle:Default:confirmEmail }

acts_camdram_security_settings_res:
    prefix: /settings
    resource: routing/settings.yml