acts_camdram_security_login:
    pattern:   /login
    defaults:  {  _controller: ActsCamdramSecurityBundle:Default:login }
acts_camdram_security_login_check:
    pattern:   /login_check
acts_camdram_security_link_user:
    pattern:   /link-user
    defaults: { _controller: ActsCamdramSecurityBundle:Default:linkUser }
acts_camdram_security_create_account:
    pattern:   /create-account
    defaults: { _controller: ActsCamdramSecurityBundle:Default:createAccount }