parameters:
#    acts_camdram.example.class: Acts\CamdramBundle\Example

services:
    camdram.security.utils:
        class: Acts\CamdramSecurityBundle\Security\SecurityUtils
        arguments: ['@service_container']

    camdram.security.user_linker:
        class: Acts\CamdramSecurityBundle\Security\UserLinker
        arguments: ['@doctrine.orm.entity_manager']

    camdram.security.registration.form:
        class: 'Symfony\Component\Form\Form'
        factory: 'Acts\CamdramSecurityBundle\Form\RegistrationFormHandler:createForm'

    camdram.security.acl.provider:
        class: Acts\CamdramSecurityBundle\Security\Acl\AclProvider
        arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher']
        public: true

    camdram.security.acl.helper:
        class: Acts\CamdramSecurityBundle\Security\Acl\Helper
        arguments: ['@security.authorization_checker', '@camdram.security.acl.provider']
        public: true

    camdram.security.token_generator: '@Acts\CamdramSecurityBundle\Service\TokenGenerator'

    Acts\CamdramSecurityBundle\EventListener\EmailSendListener:
        tags:
            - { name: kernel.event_listener, event: hwi_oauth.registration.completed, method: onRegistrationEvent }
            - { name: kernel.event_listener, event: camdram_security.ace_created, method: onAceCreatedEvent }
            - { name: kernel.event_listener, event: camdram_security.pending_access_created, method: onPendingAccessCreatedEvent }

    camdram.security.listener.ace:
        class: Acts\CamdramSecurityBundle\EventListener\AccessControlEntryListener
        arguments: ['@monolog.logger.camdram']
        tags:
            - { name: doctrine.orm.entity_listener }

    camdram.security.listener.pending_access:
        class: Acts\CamdramSecurityBundle\EventListener\PendingAccessListener
        arguments: ['@monolog.logger.camdram']
        tags:
            - { name: doctrine.orm.entity_listener }

    camdram.security.listener.user:
        class: Acts\CamdramSecurityBundle\EventListener\UserListener
        arguments: ['@doctrine.orm.entity_manager', '@Acts\CamdramSecurityBundle\Service\EmailDispatcher', '@camdram.security.token_generator']
        tags:
            - { name: doctrine.orm.entity_listener }

    Acts\CamdramSecurityBundle\EventListener\LastLoginTimeListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }