parameters:
#    acts_camdram.example.class: Acts\CamdramBundle\Example

services:
    camdram.security.authentication.listener:
        class:  Acts\CamdramSecurityBundle\Security\Firewall\CamdramListener
        parent: security.authentication.listener.abstract
        public: false
        abstract: true
        calls:
            - [setRouter, [@router]]

    camdram.security.encoder.legacy_md5:
        class:  Acts\CamdramSecurityBundle\Security\Encoder\LegacyMd5Encoder

    camdram.security.utils:
        class: Acts\CamdramSecurityBundle\Security\SecurityUtils
        arguments: [@service_container]

    camdram.security.name_utils:
        class: Acts\CamdramSecurityBundle\Security\NameUtils
        arguments: [@doctrine.orm.entity_manager]

    camdram.security.twig.extension:
        class: Acts\CamdramSecurityBundle\Twig\Extension\CamdramSecurityExtension
        arguments: [@camdram.security.utils]
        tags: [{ name: twig.extension }]

    camdram.security.type.graduation_year:
        class: Acts\CamdramSecurityBundle\Form\Type\GraduationYearType
        arguments: ~
        tags:
            - { name: form.type, alias: graduation_year }

    camdram.security.type.occupation:
        class: Acts\CamdramSecurityBundle\Form\Type\OccupationType
        arguments: ~
        tags:
            - { name: form.type, alias: occupation }

    camdram.security.acl.provider:
        class: Acts\CamdramSecurityBundle\Security\Acl\AclProvider
        arguments: [@doctrine.orm.entity_manager]

    camdram.security.acl.helper:
        class: Acts\CamdramSecurityBundle\Security\Acl\Helper
        arguments: [@security.context, @camdram.security.acl.provider]

    camdram.security.user.provider:
        class: Acts\CamdramSecurityBundle\Security\User\CamdramUserProvider
        arguments: [@doctrine.orm.entity_manager]

    camdram.security.external_user.provider:
        class: Acts\CamdramSecurityBundle\Security\User\ExternalLoginUserProvider
        arguments: [@doctrine.orm.entity_manager]

    ### Authorization voters

    camdram.security.voter.create:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\CreateVoter
        tags:
            - { name: security.voter }

    camdram.security.voter.admin:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\AdminVoter
        tags:
            - { name: security.voter }

    camdram.security.voter.editor:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\EditorVoter
        tags:
            - { name: security.voter }

    camdram.security.voter.owner:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\OwnerVoter
        arguments: [@camdram.security.acl.provider]
        tags:
            - { name: security.voter }

    camdram.security.voter.show:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\ShowVoter
        arguments: [@camdram.security.acl.provider]
        tags:
            - { name: security.voter }

    camdram.security.voter.profile:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\ProfileVoter
        tags:
            - { name: security.voter }