parameters:
#    acts_camdram.example.class: Acts\CamdramBundle\Example

services:
    camdram.security.authentication.listener:
        class:  Acts\CamdramSecurityBundle\Security\Firewall\CamdramListener
        parent: security.authentication.listener.abstract
        public: false
        abstract: true
        calls:
            - [setRouter, [@router]]

    camdram.security.service.abstract:
        class: Acts\CamdramSecurityBundle\Security\Service\AbstractService
        arguments: [@buzz.client, @security.http_utils]
        abstract: true

    camdram.security.service.facebook:
        class: Acts\CamdramSecurityBundle\Security\Service\FacebookService
        parent: camdram.security.service.abstract
        calls:
              - [setApi, [@camdram.security.api.facebook] ]

    camdram.security.service.twitter:
            class: Acts\CamdramSecurityBundle\Security\Service\TwitterService
            parent: camdram.security.service.abstract
            calls:
                  - [setApi, [@camdram.security.api.twitter] ]
                  - [setSession, [@session] ]

    camdram.security.service.raven:
        class: Acts\CamdramSecurityBundle\Security\Service\RavenService
        parent: camdram.security.service.abstract
        calls:
              - [setApi, [@camdram.security.api.raven] ]

    camdram.security.new_identity_handler:
        class: Acts\CamdramSecurityBundle\Security\Firewall\NewIdentityHandler
        arguments: [@security.context, @doctrine.orm.entity_manager, @camdram.security.service_map, @security.user_checker, @camdram.security.name_utils, @session, @router]
        abstract: true

    camdram.security.authentication.provider:
        class:  Acts\CamdramSecurityBundle\Security\Authentication\Provider\CamdramProvider
        arguments: [@camdram.security.user.provider, @camdram.security.service_map, @router, @security.user_checker]
        abstract: true

    camdram.security.service_map:
        class: Acts\CamdramSecurityBundle\Security\ServiceMap
        arguments: [@service_container, @security.http_utils, %camdram.security.services%, ~]
        abstract: true

    camdram.security.user.provider:
        class: Acts\CamdramSecurityBundle\Security\User\CamdramUserProvider
        arguments: [@doctrine.orm.entity_manager]

    camdram.security.entry_point:
        class: Acts\CamdramSecurityBundle\Security\EntryPoint\CamdramEntryPoint
        arguments: [@security.http_utils]

    camdram.security.utils:
        class: Acts\CamdramSecurityBundle\Security\SecurityUtils
        arguments: [@service_container]

    camdram.security.name_utils:
        class: Acts\CamdramSecurityBundle\Security\NameUtils

    camdram.security.api.facebook:
        class: Acts\CamdramSecurityBundle\Security\Api\FacebookApi
        arguments:
              - appId: %camdram.security.facebook.app_id%
                secret: %camdram.security.facebook.secret%
                cookie: %camdram.security.facebook.cookie%
                domain: %camdram.security.facebook.domain%
              - @session

    camdram.security.api.twitter:
        class: TwitterOAuth
        arguments:
            consumer_key: %camdram.security.twitter.consumer_key%
            consumer_secret: %camdram.security.twitter.consumer_secret%
            oauth_token: %camdram.security.twitter.access_token%
            oauth_token_secret: %camdram.security.twitter.access_token_secret%

    camdram.security.api.raven:
        class: Acts\CamdramSecurityBundle\Security\Api\RavenApi