acts_camdram_legacy_homepage:
    path:  /hello/{name}
    defaults: { _controller: ActsCamdramLegacyBundle:Default:index }
acts_camdram_legacyapi_show:
    path: /showdata.php
    defaults: { _controller: ActsCamdramLegacyBundle:LegacyApi:show, type: xml }
    requirements: { type: (xml) }
    methods: [GET]
