acts_camdram_externallogin:
  path: /extlogin
  defaults: { _controller: ActsCamdramLegacyBundle:ExternalLogin:default }
  
acts_camdram_externallogin_auth:
  path: /extlogin/auth
  defaults: { _controller: ActsCamdramLegacyBundle:ExternalLogin:auth }
  
acts_camdram_externallogin_spend:
  path: /spendtoken.php
  defaults: { _controller: ActsCamdramLegacyBundle:ExternalLogin:spendToken }