acts_camdram_api_homepage:
    path:  /
    defaults: { _controller: Acts\CamdramApiBundle\Controller\DefaultController::indexAction }

acts_camdram_api_test_console:
    path:  /test-console
    defaults: { _controller: Acts\CamdramApiBundle\Controller\DefaultController::testConsoleAction }

acts_camdram_api_annotation:
    resource: '@ActsCamdramApiBundle/Controller/'
    type: annotation
