imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    esi: { enabled: true }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%locale%"
    trusted_proxies: ['127.0.0.1']
    session:
        name: camdram
    fragments: { path: /_fragment }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'HoyesImageManagerBundle:Form:fields.html.twig'
            - 'ActsCamdramBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ActsCamdramBundle ]
    ruby: %ruby_bin%
    filters:
        cssrewrite:
            apply_to: '\.css$'
        compass:
            plugins: ['zurb-foundation']
            bin: %ruby_bin_dir%/compass
            apply_to: "\.scss$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum:       string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool  : { type: memory }
    sender_address: %mailer_sender_address%

sensio_framework_extra:
    view:    { annotations: false }

fos_rest:
    view:
        formats:
            rss: true
            xml: true
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        view_response_listener: 'force'
        failed_validation: HTTP_BAD_REQUEST
    body_listener: true
    format_listener: true
    access_denied_listener: true

acts_camdram:
    search_provider: %search_provider%
    techies_advert_default_days: 15
    techies_advert_max_days: 40

acts_social_api:
      http_client:
          timeout: 30,
          user_agent: 'Camdram.net - websupport@camdram.net'
      apis:
          facebook:
              client_id: %facebook_id%
              client_secret: %facebook_secret%
          twitter:
              client_id: %twitter_key%
              client_secret: %twitter_secret%
              access_token: %twitter_token%
              access_token_secret: %twitter_token_secret%
          google:
              client_id: %google_client_id%
              client_secret: %google_client_secret%
          google_simple:
              key: %google_key%
          github:
              client_id: %github_id%
              client_secret: %github_secret%

fos_oauth_server:
    db_driver:           orm
    client_class:        Acts\CamdramSecurityBundle\Entity\ExternalApp
    access_token_class:  Acts\CamdramSecurityBundle\Entity\AccessToken
    refresh_token_class: Acts\CamdramSecurityBundle\Entity\RefreshToken
    auth_code_class:     Acts\CamdramSecurityBundle\Entity\AuthCode

acts_sphinx_real_time:
    clients:
        default: ~
    indexes:
        show:
            fields: [name, description]
            attributes: {name: string, description: string, type: string, slug: string, start_at: datetime, rank: int}
            persistence:
                driver: orm
                model: Acts\CamdramBundle\Entity\Show
                listener:
                    is_indexable_callback: isIndexable
                provider: ~
                finder: ~
            config:
                min_prefix_len: 1
                prefix_fields: [name]
                enable_star: true
                dict: keywords
        venue:
            fields: [name, description]
            attributes: {name: string, short_name: string, description: string, slug: string,  type: string, rank: int}
            persistence:
                driver: orm
                model: Acts\CamdramBundle\Entity\Venue
                provider: ~
                finder: ~
            config:
                min_prefix_len: 1
                prefix_fields: [name, short_name]
                enable_star: true
                dict: keywords
        society:
            fields: [name, short_name, description]
            attributes: {name: string, short_name: string, description: string, slug: string, type: string, rank: int}
            persistence:
                driver: orm
                model: Acts\CamdramBundle\Entity\Society
                provider: ~
                finder: ~
            config:
                min_prefix_len: 1
                prefix_fields: [name, short_name]
                enable_star: true
                dict: keywords
        person:
            fields: [name, description]
            attributes: {name: string, description: string, type: string, slug: string, rank: int}
            persistence:
                driver: orm
                model: Acts\CamdramBundle\Entity\Person
                provider: ~
                finder: ~
                listener:
                    is_indexable_callback: isIndexable
            config:
                min_prefix_len: 1
                prefix_fields: [name]
                enable_star: true
                dict: keywords
        user:
            fields: [name]
            persistence:
                driver: orm
                model: Acts\CamdramBundle\Entity\User
                listener: ~
                provider: ~
                finder: ~
            config:
                min_prefix_len: 1
                enable_star: true
                dict: keywords

fos_js_routing:
    routes_to_expose: [ "get_[a-z]+", 'acts_camdram_diary.*', 'autocomplete_entity' ]
    
acts_time_mock:
    time_override: %current_time%

parameters:
    security.authentication.trust_resolver.class: Acts\ExternalLoginBundle\Security\Authentication\AuthenticationTrustResolver