imports:
    - { resource: config.yml }


doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: camdram
                driver: pdo_sqlite
                path: "%kernel.cache_dir%/test.db"

monolog:
    handlers: ~

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

swiftmailer:
    disable_delivery: true

fos_js_routing:
    request_context_base_url: /app_test.php

assetic:
    debug: false
    use_controller: false

ewz_recaptcha:
    enabled: false

fos_elastica:
    indexes:
        autocomplete:
            index_name: "%search_namespace%_autocomplete_test"