parameters:
    env(DATABASE_URL): "sqlite:///%kernel.cache_dir%/test.db"
    search_use_alias: false

imports:
    - { resource: config.yml }

monolog:
    handlers: ~

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    assets:
        json_manifest_path: ~

swiftmailer:
    disable_delivery: true

fos_js_routing:
    request_context_base_url: /app_test.php

ewz_recaptcha:
    enabled: false
