imports:
    - { resource: config.yml }
    - { resource: parameters.test.yml }

doctrine:
    dbal:
        dbname:   "%test_database_name%"
        user:     "%test_database_user%"
        password: "%test_database_password%"

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        firephp:
            type:  firephp
            level: info

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

assetic:
    variables:
        env: [test]

fos_js_routing:
    request_context_base_url: /app_test.php

acts_camdram:
    search_provider: doctrine

acts_sphinx_real_time:
    enabled: false

acts_time_mock:
    time_override: "2001-02-27 12:30:07"

acts_external_login:
    test: true