imports:
    - { resource: config.yml }


doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: camdram
                driver: pdo_sqlite
                path: ~
                memory: true

monolog:
    handlers: ~

framework:
    test: ~
    session:
        storage_id: acts_camdram_admin.test.session_storage
    profiler:
        enabled: true

swiftmailer:
    disable_delivery: true

fos_js_routing:
    request_context_base_url: /app_test.php

assetic:
    debug: false
    use_controller: false

ewz_recaptcha:
    enabled: false