imports:
    - { resource: config.yml }


doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: camdram
                driver: pdo_sqlite
                path: ~
                memory: true

monolog:
    handlers: ~

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_test.yml" }
    test: ~
    session:
        storage_id: acts_camdram_backend.test.session_storage
    profiler:
        enabled: true

swiftmailer:
    disable_delivery: true

fos_js_routing:
    request_context_base_url: /app_test.php

acts_time_mock:
    time_override: 2000-07-03 15:30

assetic:
    debug: false
    use_controller: false

ewz_recaptcha:
    enabled: false