parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            "default secret"

    facebook_id:                1234
    facebook_secret:            s3cr3t
    twitter_key:                1234
    twitter_secret:             s3cr3t
    twitter_token:              1234
    twitter_token_secret:       s3cr3t
    google_client_id:           1234
    google_client_secret:       s3cr3t
    
    baseurl: http://www.camdram.net