acts_camdram_backend:
    resource: "@ActsCamdramBackendBundle/Resources/config/routing.yml"
    prefix:   /

acts_camdram:
    resource: "@ActsCamdramBundle/Resources/config/routing.yml"
    prefix:   /

acts_camdram_security:
    resource: "@ActsCamdramSecurityBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
_security_check:
      pattern:  /login_check
_security_logout:
      pattern:  /logout

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

hoyes_image_manager_bundle:
    resource: "@HoyesImageManagerBundle/Resources/config/routing.yml"
    prefix: /images