_main:
    resource: routing.yml

acts_camdram_security:
    resource: "@ActsCamdramSecurityBundle/Resources/config/routing.yml"
    prefix:   /auth
    schemes:  ~
    
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    schemes:  ~

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    schemes:  ~