cmf_routing_auto:
    mappings:
        Acts\CamdramBundle\Document\Page:
            content_path:
                pages:
                    provider: [specified, {path: /cms/routes/page/infobase}]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, {method: getSlug}]
                exists_action: [auto_increment, {pattern: -%d}]
                not_exists_action: create

