security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EDITOR]
        ROLE_EDITOR:      [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        camdram:
            id: camdram.security.user.provider
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        public:
            pattern: ^/.*
            anonymous: true
            switch_user: { role: ROLE_ADMIN, parameter: _switch_to_user }
            logout:
                path: /logout
                target: /
            camdram:
                services:
                    raven: ~
                    facebook: ~
                    local: {display_name: 'Camdram Password'}
            remember_me:
                key:      %secret%
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
#        - { path ^/.*\.(json|xml)$, roles: ROLE_API }
        - { path ^/settings.*, roles: IS_AUTHENTICATED_FULLY }

acts_camdram_security:
    groups:
        admin:
            roles: [ROLE_ADMIN]
        editor:
            roles: [ROLE_EDITOR]
    services:
        facebook:
            class: social_api
            id: facebook
        twitter:
            class: social_api
            id: twitter
        google:
            class: social_api
            id: google
        raven:
            class: raven
            description: "camdram.net"
        local:
            class: local
