jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        camdram:
            id: camdram.security.user.provider
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            camdram:
                services:
                  facebook: {display_name: Facebook}
        public:
            pattern: ^/.*
            anonymous: true
            switch_user: { role: ROLE_ADMIN, parameter: _switch_to_user }
            logout:
                path: /logout
                target: /
            camdram:
                services:
                    raven: ~
                    facebook: ~
                    local: {display_name: 'Password'}
            remember_me:
                key:      Vns2DsEhoEC5EZIHUs4Qz28BER6f2AeP0V
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
#        - { path ^/.*\.(json|xml)$, roles: ROLE_API }
        - { path ^/settings.*, roles: IS_AUTHENTICATED_FULLY }
        - { path ^/admin.*, roles: ROLE_ADMIN }
    acl:
        connection: default
        voter:
            allow_if_object_identity_unavailable: false

acts_camdram_security:
    groups:
        admin:
            roles: [ROLE_ADMIN]
        editor:
            roles: [ROLE_EDITOR]
    services:
        facebook:
            class: social_api
            id: facebook
        twitter:
            class: social_api
            id: twitter
        google:
            class: social_api
            id: google
        raven:
            class: raven
            description: "camdram.net"
        local:
            class: local