jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        camdram:
            id: camdram.security.user.provider
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        public:
            pattern: ^/.*
            anonymous: true
            logout:
                path: /logout
                target: /
            camdram:
                services:
                    facebook: /login/facebook
                    twitter: /login/twitter
                    raven: /login/raven
                    google: /login/google
                    windows_live: /login/windows_live
                    yahoo: /login/yahoo
                    local: /login/local
            remember_me:
                key:      Vns2DsEhoEC5EZIHUs4Qz28BER6f2AeP0V
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path ^/settings.*, roles: IS_AUTHENTICATED_FULLY }
    acl:
        connection: default