version: '3'

services:
   db:
      image: "mariadb:10.3"
      volumes:
        - dbdata:/var/lib/mysql
      environment:
        - "MYSQL_ROOT_PASSWORD=root"
      networks:
        - default
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
      volumes:
        - esdata:/usr/share/elasticsearch/data
      environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      networks:
        - default
   web:
      build: ./
      volumes:
        - ../:/var/www/html
      ports:
        - '8000:80'
      environment:
        - "APACHE_DOCUMENT_ROOT=/var/www/html/web"
      restart: always
      networks:
        - default
volumes:
  esdata:
    driver: local
  dbdata:
    driver: local