acts_camdram_homepage:
    pattern:  /
    defaults: { _controller: ActsCamdramBundle:Default:index }
acts_camdram_shows:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\ShowController"
acts_camdram_people:
    type:     rest
    resource: Acts\CamdramBundle\Controller\PersonController
acts_camdram_societies:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\SocietyController"
acts_camdram_termdates:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\TermDateController"
acts_camdram_venues_map:
    pattern: /venues/map/{slug}
    defaults: { _controller: ActsCamdramBundle:Venue:map, slug: ~ }
acts_camdram_venues:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\VenueController"
acts_camdram_entity_toolbar:
    pattern: /entities/toolbar
    defaults: { _controller: ActsCamdramBundle:Entity:toolbar }
acts_camdram_entities:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\EntityController"
acts_camdram_settings:
    pattern: /settings
    defaults: { _controller: ActsCamdramBundle:Account:settings }
acts_camdram_login:
    pattern: /login
    defaults: { _controller: ActsCamdramBundle:Default:login }
acts_camdram_news:
    pattern: /news
    defaults: { _controller: ActsCamdramBundle:News:index }
