acts_camdram_entities_res:
    resource: "routing/entities.yml"
    type: rest
acts_camdram_diary:
    path: diary.{_format}
    defaults:
        _controller: ActsCamdramBundle:Diary:index
        _format: html
acts_camdram_diary_res:
    resource: "routing/diary.yml"
    prefix: /diary
acts_camdram_development:
    resource: "routing/development.yml"
    prefix: /development
acts_camdram_homepage:
    path:  /
    defaults: { _controller: ActsCamdramBundle:Default:index }
acts_camdram_play:
    path: /plays/{mid}
    defaults: { _controller: ActsCamdramBundle:Play:display }
    requirements:
        mid: .*
acts_camdram_contact:
    resource: "routing/contact_us.yml"
acts_camdram_privacy:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ActsCamdramBundle:Static:privacy.html.twig'
acts_camdram_roles:
    type:     rest
    prefix:   /
    resource: Acts\CamdramBundle\Controller\RoleController
acts_camdram_signinsheet:
    path: /shows/{slug}/signinsheet.{_format}
    defaults: { _controller: ActsCamdramBundle:Signinsheet:index, slug: ~, _format: html }
    requirements: { _format: (csv|html) }
    methods: [GET]
acts_camdram_about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ActsCamdramBundle:Static:about.html.twig'
acts_camdram_faq:
    path: /faq
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ActsCamdramBundle:Static:faq.html.twig'
acts_camdram_infobase_placeholder:
    path: /infobase-placeholder
    defaults:
        _controller: FrameworkBundle:Template:template
        template: ActsCamdramBundle:InfobasePlaceholder:index.html.twig
