acts_camdram_homepage:
    pattern:  /
    defaults: { _controller: ActsCamdramBundle:Default:index }
acts_camdram_shows:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\ShowController"
acts_camdram_people:
    type:     rest
    resource: Acts\CamdramBundle\Controller\PersonController
acts_camdram_socities:
    type:     rest
    resource: "Acts\CamdramBundle\Controller\SocietyController"
acts_camdram_settings:
    pattern: /settings
    defaults: { _controller: ActsCamdramBundle:Account:settings }
acts_camdram_login:
    pattern: /login
    defaults: { _controller: ActsCamdramBundle:Default:login }
