acts_camdram_homepage:
    pattern:  /
    defaults: { _controller: ActsCamdramBundle:Default:index }
acts_camdram_entities_res:
    resource: "routing/entities.yml"
acts_camdram_admin_res:
    resource: "routing/admin.yml"
    prefix: /admin
acts_camdram_settings:
    pattern: /settings
    defaults: { _controller: ActsCamdramBundle:Account:settings }
acts_camdram_login:
    pattern: /login
    defaults: { _controller: ActsCamdramBundle:Default:login }
acts_camdram_news:
    pattern: /news
    defaults: { _controller: ActsCamdramBundle:News:index }