acts_camdram_entities_res:
    resource: "routing/entities.yml"
acts_camdram_admin_res:
    resource: "routing/admin.yml"
    prefix: /admin
acts_camdram_diary:
    resource: "routing/diary.yml"
    prefix: /diary
acts_camdram_development:
    resource: "routing/development.yml"
    prefix: /development
acts_camdram_settings:
    pattern: /settings
    defaults: { _controller: ActsCamdramBundle:Account:settings }
acts_camdram_homepage:
    pattern:  /
    defaults: { _controller: ActsCamdramBundle:Default:index }