parameters:
#    acts_camdram.example.class: Acts\CamdramBundle\Example

services:
    acts.camdram.twig.camdram_extension:
        class: Acts\CamdramBundle\Twig\CamdramExtension
        arguments: [@acts.camdram.service.text]
        tags:
            - { name: twig.extension }

    acts.camdram.service.text:
        class: Acts\CamdramBundle\Service\TextService

    acts.camdram.type.college:
        class: Acts\CamdramBundle\Form\Type\CollegeType
        arguments: ~
        tags:
            - { name: form.type, alias: college }

    acts.camdram.type.facebook_link:
        class: Acts\CamdramBundle\Form\Type\FacebookLinkType
        arguments: [@acts.social_api.apis.facebook]
        tags:
            - { name: form.type, alias: facebook_link }

    acts.camdram.type.twitter_link:
        class: Acts\CamdramBundle\Form\Type\TwitterLinkType
        arguments: [@acts.social_api.apis.twitter]
        tags:
            - { name: form.type, alias: twitter_link }

    acts.camdram.type.map_location:
        class: Acts\CamdramBundle\Form\Type\MapLocationType
        arguments: [@ivory_google_map.map=, %map_center%]
        tags:
            - { name: form.type, alias: map_location }

    acts.camdram.type.entity_search:
        class: Acts\CamdramBundle\Form\Type\EntitySearchType
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: entity_search }

    acts.camdram.type.entity_collection:
        class: Acts\CamdramBundle\Form\Type\EntityCollectionType
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: entity_collection }

    acts.camdram.type.grant_type:
        class: Acts\CamdramBundle\Form\Type\GrantType
        tags:
            - { name: form.type, alias: grant_type }

    acts.camdarm.type.guesser:
        class: Acts\CamdramBundle\Form\CamdramTypeGuesser
        arguments: ~
        tags:
            - { name: form.type_guesser }

    acts.camdram.type.form_extension:
        class: Acts\CamdramBundle\Form\CamdramFormTypeExtension
        tags:
            - { name: form.type_extension, alias: form }

    acts.camdram.paginator_response_listener:
        class: Acts\CamdramBundle\Rest\EventListener\ViewPaginatorListener
        arguments: [@router]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 105 }

    acts.camdram.search_provider.doctrine:
        class: Acts\CamdramBundle\Service\Search\DoctrineProvider
        arguments: [@service_container]

    acts.camdram.search_provider.elasticsearch:
        class: Acts\CamdramBundle\Service\Search\ElasticsearchProvider
        arguments: [@service_container]