acts_camdram_issues:
    type:     rest
    resource: "Acts\CamdramAdminBundle\Controller\SupportController"

acts_camdram_users:
    type:     rest
    resource: "Acts\CamdramAdminBundle\Controller\UserController"

acts_camdram_logs_index:
    path: /logs
    defaults:
        _controller: ActsCamdramAdminBundle:Log:index

acts_camdram_logs_get:
    path: /logs/{file}
    defaults:
        _controller: ActsCamdramAdminBundle:Log:get