services:

    acts_camdram_admin.people_merger:
        class: Acts\CamdramAdminBundle\Service\PeopleMerger
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']

    acts_camdram_admin.user_merger:
        class: Acts\CamdramAdminBundle\Service\UserMerger
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']
        public: true
    
    acts_camdram_admin.test.session_storage:
        class: Acts\CamdramAdminBundle\Tests\SessionStorage
        parent: session.storage.mock_file