parameters:
    acts.diary.factory.class: Acts\DiaryBundle\Diary\DiaryFactory
    acts.diary.renderer.html.class: Acts\DiaryBundle\Diary\Renderer\HtmlRenderer

services:
    acts.diary.factory:
        class: %acts.diary.factory.class%

    acts.diary.renderer.html:
        class: %acts.diary.renderer.html.class%
        arguments: [@twig]