services:
    acts.diary.factory:
        class: Acts\DiaryBundle\Diary\DiaryFactory

    acts.diary.renderer.html:
        class: Acts\DiaryBundle\Diary\Renderer\HtmlRenderer
        arguments: ['@twig']

    acts.diary.twig_extension:
        class: Acts\DiaryBundle\Twig\DiaryExtension
        tags:
            - { name: twig.extension }
